-- Create site_settings table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.site_settings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zesco_rate NUMERIC DEFAULT 2.50,
    support_phone TEXT DEFAULT '0974300472',
    commission_rate NUMERIC DEFAULT 5.00,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed with initial settings if table is empty
INSERT INTO public.site_settings (id, zesco_rate, support_phone, commission_rate)
OVERRIDING SYSTEM VALUE
SELECT 1, 2.50, '0750264037', 5.00
WHERE NOT EXISTS (SELECT 1 FROM public.site_settings LIMIT 1);

-- Enable RLS
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Public can view site settings" ON public.site_settings;
CREATE POLICY "Public can view site settings" 
ON public.site_settings FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Admins can update site settings" ON public.site_settings;
CREATE POLICY "Admins can update site settings" 
ON public.site_settings FOR ALL 
USING (
    EXISTS (
        SELECT 1 FROM profiles 
        WHERE id = auth.uid() AND role = 'admin'
    )
);

-- Grant permissions
GRANT SELECT ON public.site_settings TO anon, authenticated;
GRANT ALL ON public.site_settings TO service_role;
